// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/grpc/proto/restaurant.proto

package restaurant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Макроэлементы для блюда
type Macros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calories      float32                `protobuf:"fixed32,1,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins      float32                `protobuf:"fixed32,2,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats          float32                `protobuf:"fixed32,3,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbohydrates float32                `protobuf:"fixed32,4,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Macros) Reset() {
	*x = Macros{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Macros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Macros) ProtoMessage() {}

func (x *Macros) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Macros.ProtoReflect.Descriptor instead.
func (*Macros) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *Macros) GetCalories() float32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *Macros) GetProteins() float32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *Macros) GetFats() float32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *Macros) GetCarbohydrates() float32 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

// Блюдо
type Dish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                      // id
	MenuId        string                 `protobuf:"bytes,2,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"` // uuid
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Compound      string                 `protobuf:"bytes,4,opt,name=compound,proto3" json:"compound,omitempty"`
	Macros        *Macros                `protobuf:"bytes,5,opt,name=macros,proto3" json:"macros,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *Dish) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetMenuId() string {
	if x != nil {
		return x.MenuId
	}
	return ""
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetCompound() string {
	if x != nil {
		return x.Compound
	}
	return ""
}

func (x *Dish) GetMacros() *Macros {
	if x != nil {
		return x.Macros
	}
	return nil
}

func (x *Dish) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Dish) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Меню
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // uuid
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"` // uuid
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	DishList      []*Dish                `protobuf:"bytes,5,rep,name=dish_list,json=dishList,proto3" json:"dish_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *Menu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *Menu) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Menu) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Menu) GetDishList() []*Dish {
	if x != nil {
		return x.DishList
	}
	return nil
}

// Ресторан
type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	MenuList      []*Menu                `protobuf:"bytes,4,rep,name=menu_list,json=menuList,proto3" json:"menu_list,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Restaurant) GetMenuList() []*Menu {
	if x != nil {
		return x.MenuList
	}
	return nil
}

func (x *Restaurant) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RestaurantIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantIdRequest) Reset() {
	*x = RestaurantIdRequest{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantIdRequest) ProtoMessage() {}

func (x *RestaurantIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantIdRequest.ProtoReflect.Descriptor instead.
func (*RestaurantIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *RestaurantIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MenuIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuIdRequest) Reset() {
	*x = MenuIdRequest{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuIdRequest) ProtoMessage() {}

func (x *MenuIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuIdRequest.ProtoReflect.Descriptor instead.
func (*MenuIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *MenuIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DishIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishIdRequest) Reset() {
	*x = DishIdRequest{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishIdRequest) ProtoMessage() {}

func (x *DishIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishIdRequest.ProtoReflect.Descriptor instead.
func (*DishIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *DishIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	MenuList      []*Menu                `protobuf:"bytes,3,rep,name=menu_list,json=menuList,proto3" json:"menu_list,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *CreateRestaurantRequest) GetMenuList() []*Menu {
	if x != nil {
		return x.MenuList
	}
	return nil
}

func (x *CreateRestaurantRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurant    *Restaurant            `protobuf:"bytes,2,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantRequest) Reset() {
	*x = UpdateRestaurantRequest{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantRequest) ProtoMessage() {}

func (x *UpdateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type IdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReply) Reset() {
	*x = IdReply{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReply) ProtoMessage() {}

func (x *IdReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReply.ProtoReflect.Descriptor instead.
func (*IdReply) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *IdReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReply) Reset() {
	*x = MessageReply{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReply) ProtoMessage() {}

func (x *MessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReply.ProtoReflect.Descriptor instead.
func (*MessageReply) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *MessageReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestaurantList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantList) Reset() {
	*x = RestaurantList{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantList) ProtoMessage() {}

func (x *RestaurantList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantList.ProtoReflect.Descriptor instead.
func (*RestaurantList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *RestaurantList) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type MenuList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*Menu                `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuList) Reset() {
	*x = MenuList{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuList) ProtoMessage() {}

func (x *MenuList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuList.ProtoReflect.Descriptor instead.
func (*MenuList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{12}
}

func (x *MenuList) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type DishList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishList) Reset() {
	*x = DishList{}
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishList) ProtoMessage() {}

func (x *DishList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_restaurant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishList.ProtoReflect.Descriptor instead.
func (*DishList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_restaurant_proto_rawDescGZIP(), []int{13}
}

func (x *DishList) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

var File_internal_grpc_proto_restaurant_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_restaurant_proto_rawDesc = "" +
	"\n" +
	"$internal/grpc/proto/restaurant.proto\x12\vrestaurants\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x06Macros\x12\x1a\n" +
	"\bcalories\x18\x01 \x01(\x02R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x02 \x01(\x02R\bproteins\x12\x12\n" +
	"\x04fats\x18\x03 \x01(\x02R\x04fats\x12$\n" +
	"\rcarbohydrates\x18\x04 \x01(\x02R\rcarbohydrates\"\xbe\x01\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\amenu_id\x18\x02 \x01(\tR\x06menuId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcompound\x18\x04 \x01(\tR\bcompound\x12+\n" +
	"\x06macros\x18\x05 \x01(\v2\x13.restaurants.MacrosR\x06macros\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\"\xa5\x01\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12.\n" +
	"\tdish_list\x18\x05 \x03(\v2\x11.restaurants.DishR\bdishList\"\x8c\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12.\n" +
	"\tmenu_list\x18\x04 \x03(\v2\x11.restaurants.MenuR\bmenuList\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"%\n" +
	"\x13RestaurantIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rMenuIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDishIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x89\x01\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x02 \x01(\tR\x04logo\x12.\n" +
	"\tmenu_list\x18\x03 \x03(\v2\x11.restaurants.MenuR\bmenuList\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"b\n" +
	"\x17UpdateRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\n" +
	"restaurant\x18\x02 \x01(\v2\x17.restaurants.RestaurantR\n" +
	"restaurant\"\x19\n" +
	"\aIdReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\fMessageReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x0eRestaurantList\x129\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x17.restaurants.RestaurantR\vrestaurants\"3\n" +
	"\bMenuList\x12'\n" +
	"\x05menus\x18\x01 \x03(\v2\x11.restaurants.MenuR\x05menus\"5\n" +
	"\bDishList\x12)\n" +
	"\x06dishes\x18\x01 \x03(\v2\x11.restaurants.DishR\x06dishes2\xa0\x03\n" +
	"\x11RestaurantService\x12E\n" +
	"\x0eGetRestaurants\x12\x16.google.protobuf.Empty\x1a\x1b.restaurants.RestaurantList\x12N\n" +
	"\x11GetRestaurantById\x12 .restaurants.RestaurantIdRequest\x1a\x17.restaurants.Restaurant\x12N\n" +
	"\x10CreateRestaurant\x12$.restaurants.CreateRestaurantRequest\x1a\x14.restaurants.IdReply\x12S\n" +
	"\x10UpdateRestaurant\x12$.restaurants.UpdateRestaurantRequest\x1a\x19.restaurants.MessageReply\x12O\n" +
	"\x10DeleteRestaurant\x12 .restaurants.RestaurantIdRequest\x1a\x19.restaurants.MessageReply2H\n" +
	"\vMenuService\x129\n" +
	"\bGetMenus\x12\x16.google.protobuf.Empty\x1a\x15.restaurants.MenuList2I\n" +
	"\vDishService\x12:\n" +
	"\tGetDishes\x12\x16.google.protobuf.Empty\x1a\x15.restaurants.DishListB=Z;github.com/failfilin/otus_hw/internal/grpc/proto;restaurantb\x06proto3"

var (
	file_internal_grpc_proto_restaurant_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_restaurant_proto_rawDescData []byte
)

func file_internal_grpc_proto_restaurant_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_restaurant_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_restaurant_proto_rawDesc), len(file_internal_grpc_proto_restaurant_proto_rawDesc)))
	})
	return file_internal_grpc_proto_restaurant_proto_rawDescData
}

var file_internal_grpc_proto_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_grpc_proto_restaurant_proto_goTypes = []any{
	(*Macros)(nil),                  // 0: restaurants.Macros
	(*Dish)(nil),                    // 1: restaurants.Dish
	(*Menu)(nil),                    // 2: restaurants.Menu
	(*Restaurant)(nil),              // 3: restaurants.Restaurant
	(*RestaurantIdRequest)(nil),     // 4: restaurants.RestaurantIdRequest
	(*MenuIdRequest)(nil),           // 5: restaurants.MenuIdRequest
	(*DishIdRequest)(nil),           // 6: restaurants.DishIdRequest
	(*CreateRestaurantRequest)(nil), // 7: restaurants.CreateRestaurantRequest
	(*UpdateRestaurantRequest)(nil), // 8: restaurants.UpdateRestaurantRequest
	(*IdReply)(nil),                 // 9: restaurants.IdReply
	(*MessageReply)(nil),            // 10: restaurants.MessageReply
	(*RestaurantList)(nil),          // 11: restaurants.RestaurantList
	(*MenuList)(nil),                // 12: restaurants.MenuList
	(*DishList)(nil),                // 13: restaurants.DishList
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_internal_grpc_proto_restaurant_proto_depIdxs = []int32{
	0,  // 0: restaurants.Dish.macros:type_name -> restaurants.Macros
	1,  // 1: restaurants.Menu.dish_list:type_name -> restaurants.Dish
	2,  // 2: restaurants.Restaurant.menu_list:type_name -> restaurants.Menu
	2,  // 3: restaurants.CreateRestaurantRequest.menu_list:type_name -> restaurants.Menu
	3,  // 4: restaurants.UpdateRestaurantRequest.restaurant:type_name -> restaurants.Restaurant
	3,  // 5: restaurants.RestaurantList.restaurants:type_name -> restaurants.Restaurant
	2,  // 6: restaurants.MenuList.menus:type_name -> restaurants.Menu
	1,  // 7: restaurants.DishList.dishes:type_name -> restaurants.Dish
	14, // 8: restaurants.RestaurantService.GetRestaurants:input_type -> google.protobuf.Empty
	4,  // 9: restaurants.RestaurantService.GetRestaurantById:input_type -> restaurants.RestaurantIdRequest
	7,  // 10: restaurants.RestaurantService.CreateRestaurant:input_type -> restaurants.CreateRestaurantRequest
	8,  // 11: restaurants.RestaurantService.UpdateRestaurant:input_type -> restaurants.UpdateRestaurantRequest
	4,  // 12: restaurants.RestaurantService.DeleteRestaurant:input_type -> restaurants.RestaurantIdRequest
	14, // 13: restaurants.MenuService.GetMenus:input_type -> google.protobuf.Empty
	14, // 14: restaurants.DishService.GetDishes:input_type -> google.protobuf.Empty
	11, // 15: restaurants.RestaurantService.GetRestaurants:output_type -> restaurants.RestaurantList
	3,  // 16: restaurants.RestaurantService.GetRestaurantById:output_type -> restaurants.Restaurant
	9,  // 17: restaurants.RestaurantService.CreateRestaurant:output_type -> restaurants.IdReply
	10, // 18: restaurants.RestaurantService.UpdateRestaurant:output_type -> restaurants.MessageReply
	10, // 19: restaurants.RestaurantService.DeleteRestaurant:output_type -> restaurants.MessageReply
	12, // 20: restaurants.MenuService.GetMenus:output_type -> restaurants.MenuList
	13, // 21: restaurants.DishService.GetDishes:output_type -> restaurants.DishList
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_restaurant_proto_init() }
func file_internal_grpc_proto_restaurant_proto_init() {
	if File_internal_grpc_proto_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_restaurant_proto_rawDesc), len(file_internal_grpc_proto_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_grpc_proto_restaurant_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_restaurant_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_restaurant_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_restaurant_proto = out.File
	file_internal_grpc_proto_restaurant_proto_goTypes = nil
	file_internal_grpc_proto_restaurant_proto_depIdxs = nil
}
